{% set name = "oss2" %}
{% set version = "2.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: df17d6fe38deedb80bfa60ee0eecc0a1b2fa507f6aaeb8af37b22645257acfdd

build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - requests !=2.9.0
    - crcmod >=1.7
    - pycryptodome >=3.4.7
    - aliyun-python-sdk-kms >=2.4.1
    # aliyun-python-sdk-core is python2/3 compatible in recent releases
    # py3 will pull in an updated, compatible build.
    - aliyun-python-sdk-core >=2.6.2

test:
  imports:
    - oss2

about:
  home: http://oss.aliyun.com
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Aliyun OSS (Object Storage Service) SDK.
  description: |
    Alibaba Cloud Object Storage Python SDK 2.x. This version is not
    compatible with the previous version (Version 0.x). The package
    name is "oss2" to avoid conflicts with previous versions.

extra:
  recipe-maintainers:
    - shcheklein
    - efiop
    - maxhora
