{% set name = "oss2" %}
{% set version = "2.18.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/oss2-{{ version }}.tar.gz
  sha256: be1e7a871a8cc267726367333017d78333ee8fae88c727ad61396f59c1c0e4d0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - aliyun-python-sdk-core >=2.13.12
    - aliyun-python-sdk-kms >=2.4.1
    - crcmod >=1.7
    - pycryptodome >=3.4.7
    - python >=3.6
    - requests !=2.9.0
    - six

test:
  imports:
    - oss2
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://oss.aliyun.com
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Aliyun OSS (Object Storage Service) SDK.
  description: |
    Alibaba Cloud Object Storage Python SDK 2.x. This version is not
    compatible with the previous version (Version 0.x). The package
    name is "oss2" to avoid conflicts with previous versions.

extra:
  recipe-maintainers:
    - shcheklein
    - efiop
    - maxhora
